version: '3'
services:
  
  # MySQL
  mysql:
    image: mysql:8-debian
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    restart: always
  
  # WordPress
  wordpress:
    image: wordpress:php8.1-fpm
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      WORDPRESS_DB_NAME: db_wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    restart: always
  
  # Nginx
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./www:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress
