version: '3.9'

services:
  
  # MySQL
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=wp_db
    networks:
      - wordpress
  
  # WordPress
  wordpress:
    image: wordpress:php8.1-fpm
    container_name: wp
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      MYSQL_ROOT_PASSWORD: password
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    restart: always
    networks:
      - wordpress
  
  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./www:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
      - wordpress
    networks:
      - wordpress

networks:
  wordpress:
volumes:
  mysql:
